import { Component, EventEmitter, Input, OnChanges, OnInit, Output, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../../core/services/auth.service';
import { LocationService } from '../../../core/services/location.service';
import { City } from '../../models/location.model';

@Component({ selector:'app-auth-popup', standalone:true, imports:[CommonModule,FormsModule], templateUrl:'./auth-popup.component.html', styleUrl:'./auth-popup.component.css' })
export class AuthPopupComponent implements OnInit, OnChanges {
  @Input() visible=false; @Input() initialMode:'login'|'signup'|'forgot'='login';
  @Output() closed=new EventEmitter<void>(); @Output() authenticated=new EventEmitter<void>();
  authMode:'login'|'signup'|'forgot'='login'; isSubmittingAuth=false; isLoggingIn=false;
  loginUserName=''; loginPassword=''; loginErrorMessage=''; authSuccessMessage=''; showLoginPassword=false;
  signupStep:'mobile'|'otp1'|'account'='mobile'; signupPhone=''; signupOtpOne=''; signupOtpTwo=''; signupFullName=''; signupCnic=''; signupEmail=''; signupCityId:number|null=null; signupAddress=''; signupPassword=''; signupConfirmPassword=''; signupAcceptedTerms=false; showSignupPassword=false; showSignupConfirmPassword=false;
  cities:City[]=[]; isLoadingCities=false; devOtpOne=''; devOtpTwo=''; forgotIdentifier='';
  constructor(private readonly authService:AuthService,private readonly locationService:LocationService){}
  ngOnInit():void{this.loadCities();}
  ngOnChanges(_changes: SimpleChanges):void{if(this.visible){this.authMode=this.initialMode;this.resetMessages();}}
  private loadCities():void{this.isLoadingCities=true;this.locationService.getCities().subscribe({next:c=>{this.cities=c??[];this.isLoadingCities=false;},error:e=>{console.error('Auth popup city API error:',e);this.cities=[];this.isLoadingCities=false;}});}
  switchAuthMode(mode:'login'|'signup'|'forgot'):void{if(this.isSubmittingAuth)return;this.authMode=mode;this.resetMessages();if(mode==='signup'){this.signupStep='mobile';this.devOtpOne='';this.devOtpTwo='';}}
  closePopup():void{if(this.isSubmittingAuth||this.isLoggingIn)return;this.closed.emit();}
  private resetMessages():void{this.loginErrorMessage='';this.authSuccessMessage='';}
  toggleLoginPassword():void{this.showLoginPassword=!this.showLoginPassword;} toggleSignupPassword():void{this.showSignupPassword=!this.showSignupPassword;} toggleSignupConfirmPassword():void{this.showSignupConfirmPassword=!this.showSignupConfirmPassword;}
  loginFromPopup():void{this.resetMessages();if(!this.loginUserName.trim()){this.loginErrorMessage='Please enter your username.';return;}if(!this.loginPassword){this.loginErrorMessage='Please enter your password.';return;}if(this.isSubmittingAuth||this.isLoggingIn)return;this.isLoggingIn=true;this.isSubmittingAuth=true;this.authService.login({userName:this.loginUserName.trim(),password:this.loginPassword,fmcToken:'string',deviceModel:'Web Browser'}).subscribe({next:r=>{this.isLoggingIn=false;this.isSubmittingAuth=false;if(!r||r.responseStatus!==1){this.loginErrorMessage=r?.message||'Login failed. Please check your credentials.';return;}this.loginPassword='';this.authSuccessMessage='Login successful.';this.authenticated.emit();},error:e=>{this.isLoggingIn=false;this.isSubmittingAuth=false;this.loginErrorMessage=this.getErrorMessage(e,'Unable to login. Please check your username and password.');}});}
  requestSignupOtp():void{this.resetMessages();const cellNumber=this.normalizeCellNumber(this.signupPhone);if(!cellNumber){this.loginErrorMessage='Please enter your mobile number.';return;}if(cellNumber.length<10){this.loginErrorMessage='Please enter a valid mobile number.';return;}if(this.isSubmittingAuth)return;this.isSubmittingAuth=true;this.authService.requestOtp(cellNumber).subscribe({next:r=>{this.isSubmittingAuth=false;if(!r||r.responseStatus!==1){this.loginErrorMessage=r?.message||'Unable to generate OTP.';return;}this.signupPhone=cellNumber;this.devOtpOne=this.extractOtpFromMessage(r.message);this.signupStep='otp1';this.authSuccessMessage='OTP #1 generated successfully.';},error:e=>{this.isSubmittingAuth=false;this.loginErrorMessage=this.getErrorMessage(e,'Unable to send OTP. Please try again.');}});}
  validateSignupOtp():void{this.resetMessages();if(!this.signupOtpOne.trim()){this.loginErrorMessage='Please enter OTP #1.';return;}if(this.isSubmittingAuth)return;this.isSubmittingAuth=true;this.authService.validateOtp({userName:this.signupPhone,otp:this.signupOtpOne.trim(),type:0}).subscribe({next:r=>{this.isSubmittingAuth=false;if(!r||r.responseStatus!==1){this.loginErrorMessage=r?.message||'OTP #1 validation failed.';return;}this.devOtpTwo=String(r.data?.otp??'').trim();this.signupOtpTwo='';this.signupStep='account';this.authSuccessMessage='OTP #1 verified. Complete your account using OTP #2.';},error:e=>{this.isSubmittingAuth=false;this.loginErrorMessage=this.getErrorMessage(e,'Unable to validate OTP #1.');}});}
  completeSignup():void{this.resetMessages();const fullName=this.signupFullName.trim(),cnic=this.signupCnic.trim(),email=this.signupEmail.trim(),address=this.signupAddress.trim(),otpTwo=this.signupOtpTwo.trim();if(!fullName){this.loginErrorMessage='Please enter your full name.';return;}if(!cnic){this.loginErrorMessage='Please enter your CNIC.';return;}if(!email||!this.isValidEmail(email)){this.loginErrorMessage='Please enter a valid email address.';return;}if(!this.signupCityId||this.signupCityId<=0){this.loginErrorMessage='Please select your city.';return;}if(!address){this.loginErrorMessage='Please enter your address.';return;}if(this.signupPassword.length<6){this.loginErrorMessage='Password must be at least 6 characters.';return;}if(this.signupPassword!==this.signupConfirmPassword){this.loginErrorMessage='Passwords do not match.';return;}if(!otpTwo){this.loginErrorMessage='Please enter OTP #2.';return;}if(!this.signupAcceptedTerms){this.loginErrorMessage='Please accept the Terms & Conditions to continue.';return;}if(this.isSubmittingAuth)return;const fd=new FormData();fd.append('ReferralCode','');fd.append('CNIC',cnic);fd.append('UserName',this.signupPhone);fd.append('Email',email);fd.append('DisplayName',fullName);fd.append('Password',this.signupPassword);fd.append('OTP',otpTwo);fd.append('Address',address);fd.append('CityId',String(this.signupCityId));fd.append('FmcToken','string');fd.append('DeviceModel','Web Browser');this.isSubmittingAuth=true;this.authService.register(fd).subscribe({next:r=>{this.isSubmittingAuth=false;if(!r||r.responseStatus!==1){this.loginErrorMessage=r?.message||'Unable to create your account.';return;}this.authSuccessMessage=r.message||'Account created successfully.';this.authenticated.emit();},error:e=>{this.isSubmittingAuth=false;this.loginErrorMessage=this.getErrorMessage(e,'Unable to create your account.');}});}
  forgotPasswordFromPopup():void{this.resetMessages();if(!this.forgotIdentifier.trim()){this.loginErrorMessage='Please enter your email or username.';return;}this.loginErrorMessage='Forgot password API has not been provided yet.';}
  private normalizeCellNumber(value:string):string{let digits=value.replace(/\D/g,'');if(digits.startsWith('0'))digits='92'+digits.substring(1);if(!digits.startsWith('92')&&digits.length===10)digits='92'+digits;return digits;}
  private extractOtpFromMessage(message:string|undefined):string{if(!message)return '';const match=message.match(/(\d{4,8})\s*$/);return match?.[1]??'';}
  private isValidEmail(email:string):boolean{return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);}
  private getErrorMessage(error:unknown,fallback:string):string{if(error instanceof Error&&error.message)return error.message;if(typeof error==='object'&&error!==null){const e=error as {error?:{message?:string};message?:string};return e.error?.message||e.message||fallback;}return fallback;}
}
