name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Runs automatically when you push code to main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npx ng build --configuration production --base-href /Internship_order_taking_system/

      - name: Upload to GitHub Pages Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/foodie/browser # Uses the compiled folder name from your angular.json
          branch: gh-pages
